---
title: "plantas_extintas"
author: "jorge callejo"
date: "16/062022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(kableExtra)
```

## Introducción

### Estos son sobre plantas extintas son daod de *UNI*, y se obtuvieron del [siguiente repositorio de github:](https://github.com/rfordatascience/tidytuesday)


```{r, echo=FALSE}
plants <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/plants.csv")
actions <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/actions.csv")
threats <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/threats.csv")
```

## Datos de Sudamérica

El número de especies extintas que hay en sudamérica es de: `r plants %>%  dplyr::filter(continent == "South America") %>%  nrow()` especies, segun la base de datos. 

```{r, echo=FALSE}
data("msleep")
view(msleep)
tabla <- msleep %>% 
  group_by(vore) %>% 
  summarise_at(.vars = "sleep_total", .funs = list(Mean = mean, SD =sd)) %>% 
  dplyr::filter(!is.na(vore)) %>% 
  arrange(desc(Mean))

kable(tabla, digits = 2) %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)
```

```{r, echo=FALSE}
msleep_long <- msleep %>% 
  dplyr::select(name, vore,sleep_total, brainwt)

kable(msleep_long, digits = 2, caption = "La base de datos entera") %>% 
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = F) %>% 
  scroll_box(width = "800px", height = "200px")
```

